---
###############################################################################
# Filename: requirements.yml
# Role: ansible-role-rhel-rke2-stig
# Summary: Ansible Galaxy collection dependencies for this role
# Last Updated: 24 Jan 2026
# Classification: UNCLASSIFIED
###############################################################################
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"
