---
###############################################################################
# Filename: molecule/default/converge.yml
# Role: ansible-role-rhel-rke2-stig
# Summary: Apply the STIG role to test container
# Last Updated: 23 Jan 2026
# Classification: UNCLASSIFIED
###############################################################################
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  pre_tasks:
    - name: Debug role information
      ansible.builtin.debug:
        msg: "Including role: {{ role_name }} from {{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
  tasks:
    - name: Include role under test
      ansible.builtin.include_role:
        name: "{{ role_name }}"
