---
###############################################################################
# Filename: molecule/default/prepare.yml
# Role: ansible-role-rhel-rke2-stig
# Summary: Prepare test container with required packages for STIG testing
# Last Updated: 23 Jan 2026
# Classification: UNCLASSIFIED
###############################################################################
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install required packages for STIG testing
      ansible.builtin.dnf:
        name:
          - audit          # Provides auditd, /etc/audit/rules.d
          - procps-ng      # Process utilities
          - kmod           # Kernel module tools
        state: present

    - name: Ensure auditd service is enabled and started
      ansible.builtin.service:
        name: auditd
        state: started
        enabled: true
      ignore_errors: true  # May fail in container without full systemd

    - name: Display auditd service status
      ansible.builtin.command:
        cmd: systemctl status auditd
      register: auditd_status
      changed_when: false
      failed_when: false

    - name: Show auditd status
      ansible.builtin.debug:
        var: auditd_status.stdout_lines
