---
###############################################################################
# Filename: molecule/default/prepare.yml
# Role: ansible-role-rhel-rke2-stig
# Summary: Prepare test container with required packages for STIG testing
# Last Updated: 23 Jan 2026
# Classification: UNCLASSIFIED
###############################################################################
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    # Enable CentOS Stream 9 repos for packages not in UBI9
    # Uses official CentOS mirrors (SCRM compliant - NIST SP800-53 SR)
    - name: Add CentOS Stream 9 BaseOS repository
      ansible.builtin.yum_repository:
        name: centos-stream-9-baseos
        description: CentOS Stream 9 - BaseOS
        baseurl: https://mirror.stream.centos.org/9-stream/BaseOS/$basearch/os/
        gpgcheck: true
        gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
        enabled: true

    - name: Add CentOS Stream 9 AppStream repository
      ansible.builtin.yum_repository:
        name: centos-stream-9-appstream
        description: CentOS Stream 9 - AppStream
        baseurl: https://mirror.stream.centos.org/9-stream/AppStream/$basearch/os/
        gpgcheck: true
        gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
        enabled: true

    - name: Import CentOS GPG key
      ansible.builtin.rpm_key:
        key: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
        state: present

    - name: Install required packages for STIG testing
      ansible.builtin.dnf:
        name:
          - audit           # Provides auditd, /etc/audit/rules.d
          - procps-ng       # Process utilities
          - kmod            # Kernel module tools
          - fapolicyd       # Application whitelisting (RHEL-09-433016)
          - NetworkManager  # Network config (for CNI ignore rules)
          - firewalld       # Firewall service (to test disable task)
        state: present

    # Note: auditd cannot run in containers (requires kernel audit subsystem)
    # The audit package is installed for directory structure and tools only
    # Rule files will be deployed but not loaded until running on real hardware
    - name: Verify audit rules directory exists
      ansible.builtin.stat:
        path: /etc/audit/rules.d
      register: audit_rules_dir

    - name: Display audit setup status
      ansible.builtin.debug:
        msg: "Audit rules directory ready: {{ audit_rules_dir.stat.exists }}"
